# general configuration
url: https://ranery.github.io
baseurl: ''
navi: ''
# compass configuration
configs:
  # an avatar or logo (optional)
  logo: "/images/me.jpg"
  # author will appear under the avatar (optional)
  title: "Haoran You"
  # tagline will appear under the title (optional)
  tagline: "A Camel walks in the desert."
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# exclude
exclude: ["CNAME", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
